name: Generate executables and post them to release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-windows-executables:
    name: Build & publish for ${{ matrix.name }}
    runs-on: windows-latest
    strategy:
      matrix:
        name: 
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.name }}

      - name: Get app version
        id: app_version
        shell: pwsh
        run: |
          $version = (Get-Content .\Cargo.toml | Select-String -Pattern '^\s*version\s*=\s*"(\d+\.\d+\.\d+)"' | ForEach-Object { $_.Matches.Groups[1].Value })
          echo "APP_VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build release
        run: |
          cargo build --release --locked --target ${{ matrix.name }}
          mv ./target/${{ matrix.name }}/release/blest.exe ./blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.name }}.exe

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.name }}.exe
          tag_name: ${{ steps.app_version.outputs.APP_VERSION }}

  generate-linux-executables:
    name: Build & publish for ${{ matrix.target }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - stable
        target:
          - aarch64-unknown-linux-gnu
          - i586-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
        
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: matrix.target != 'i686-unknown-linux-musl' && matrix.target != 'x86_64-unknown-linux-musl'

      - name: Installing dependencies for i686-unknown-linux-musl & x86_64-unknown-linux-musl
        run: sudo apt update && sudo apt install musl-dev musl-tools -y
        if: matrix.target == 'i686-unknown-linux-musl' || matrix.target == 'x86_64-unknown-linux-musl'

      - name: Install toolchain for i686-unknown-linux-musl & x86_64-unknown-linux-musl
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
        if: matrix.target == 'i686-unknown-linux-musl' || matrix.target == 'x86_64-unknown-linux-musl'

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Get app version
        id: app_version
        run: echo "APP_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)" >> $GITHUB_OUTPUT

      - name: Build release
        run: |
          cargo build --release --locked --target ${{ matrix.target }}
          mv ./target/${{ matrix.target }}/release/blest ./blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.target }}

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        id: upload_linux_executable
        with:
          files: blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.target }}
          tag_name: ${{ steps.app_version.outputs.APP_VERSION }}

      - name: Replace placeholders in PKGBUILD
        run: |
          sed -i "s#%URL%#${{ steps.upload_linux_executable.outputs.url }}#g" build/PKGBUILD
          sed -i "s/%VERSION%/${{ steps.app_version.outputs.APP_VERSION }}/g" build/PKGBUILD
          sed -i "s/%TARGET%/${{ matrix.target }}/g" build/PKGBUILD
          sed -i "s/%EXEC_B2SUM%/$(b2sum 'blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.target }}' | awk '{print $1}')/g" build/PKGBUILD
        if: contains('aarch64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-unknown-linux-gnu', matrix.target)
      
      - name: Build pacman package
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'build/'
        if: contains('aarch64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-unknown-linux-gnu', matrix.target)

      - name: Renaming package
        run: |
          cd build
          mv *.pkg.tar.zst blest-${{ steps.app_version.outputs.APP_VERSION }}-pacman-x86_64.pkg.tar.zst
        if: contains('aarch64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-unknown-linux-gnu', matrix.target)

      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/blest-${{ steps.app_version.outputs.APP_VERSION }}-pacman-x86_64.pkg.tar.zst
          tag_name: ${{ steps.app_version.outputs.APP_VERSION }}
        if: contains('aarch64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-unknown-linux-gnu', matrix.target)

  generate-macos-executables:
    name: Build & publish for ${{ matrix.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        name: 
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Environment Setup
        run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.name }}

      - name: Get app version
        id: app_version
        run: echo "APP_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)" >> $GITHUB_OUTPUT

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build release
        run: |
          cargo build --release --locked --target ${{ matrix.name }}
          mv ./target/${{ matrix.name }}/release/blest ./blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.name }}

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: blest-${{ steps.app_version.outputs.APP_VERSION }}-${{ matrix.name }}
          tag_name: ${{ steps.app_version.outputs.APP_VERSION }}